### PR TITLE
Allow all 8.x major versions of Npgsql

### PR DESCRIPTION
**Pull request by Goltom**
## Changes
Allow all 8.x major versions of Npgsql

### CODE REVIEW

**Comment by Goltom** [comment]
@Aaronontheweb can you approve the PR (or give feedback)?

**Review by Aaronontheweb — APPROVED** [review]
LGTM

**Comment by Aaronontheweb** [comment]
Sorry for the delay @Goltom - LGTM

**Comment by Goltom** [comment]
@Aaronontheweb No problem, but it seems the change 
`<PostgresHighVersion>9</PostgresHighVersion>`
 in _Directory.Packages.props_ was overwritten by the build. Perhaps because the square brackets weren't closed properly on line 10?
 So I made a new PR: https://github.com/akkadotnet/Akka.Persistence.PostgreSql/pull/247

**Comment by Arkatufus** [comment]
@Goltom It was my bad, we will do another release as soon as possible.

**Pull request merged**
